# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('reservation_date', models.DateField(verbose_name='Date de r\xe9servation')),
                ('reservation_hour', models.TimeField(verbose_name='Heure de r\xe9servation')),
                ('start_address', models.CharField(max_length=250, verbose_name='D\xe9part')),
                ('dest_address', models.CharField(max_length=250, verbose_name='Destination')),
                ('state', models.BooleanField()),
                ('duration', models.CharField(max_length=10)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.Cars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
